---
- name: Check Windows Event Log for Warnings or Errors
  hosts: all
  tasks:
    - name: Get event log entries
      win_shell: |
        Get-WinEvent -LogName Application | Where-Object { $_.LevelDisplayName -in @('Warning', 'Error') }
      register: event_logs

    - name: Display event log results
      debug:
        msg: "{{ event_logs.stdout_lines }}"
      when: event_logs.stdout_lines | length > 0

    - name: Take action if warning or error found
      win_command: 'Write-Host "Action Taken: Review the application log."'
      when: event_logs.stdout_lines | length > 0
